package com.diconium.mobile.tools.kebabkrafter.generator

import com.squareup.kotlinpoet.FileSpec

internal const val AUTO_GENERATOR_WARNING = """

   Please note:
   
   This class is auto generated by Kebab Krafter Server Generator
   DO NOT edit this file manually.

"""

private const val INDENT = "    "
internal fun FileSpec.Builder.indent() = indent(INDENT)
