openapi: '3.0.3'

info:
  title: Parsing of data structures with arrays of enums
  version: '1.0.0'

paths:
  /edge_case_enum_array:
    get:
      tags: [ general ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './models/EnumArrayResponse.json'
