openapi: '3.0.3'

info:
  title: Parsing of names with acronyms
  version: '1.0.0'

paths:
  /edge_case_description:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: './models/DescriptionResponse.json'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './models/DescriptionResponse.json'
