openapi: '3.0.3'

info:
  title: Headers routing
  version: '1.0.0'

paths:
  /v1/some/deprecated/path:
    get:
      deprecated: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './models/NotImportant.json'
