name: "On Pull Request"

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle.properties
            **/gradle-wrapper.properties
            **/gradle/libs.versions.toml

      - name: Build - Plugin
        working-directory: kebab-krafter
        env:
          KEBAB_VERSION: 0.0.1-SNAPSHOT
        run: ./gradlew check

      - name: Build - Sample
        working-directory: sample
        env:
          KEBAB_VERSION: 0.0.1-SNAPSHOT
        run: ./gradlew check

      - name: Build - Android
        working-directory: android
        env:
          KEBAB_VERSION: 0.0.1-SNAPSHOT
        run: ./gradlew assembleDebug testDebugUnitTest
